<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>AnalogHwMonitor</AssemblyName>
    <ApplicationIcon>appicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnalogHwMonitor.Core\AnalogHwMonitor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="appicon.ico">
      <LogicalName>AnalogHwMonitor.App.appicon.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="appicon-warning.ico">
      <LogicalName>AnalogHwMonitor.App.appicon-warning.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
